//
//  ChattingPageViewController.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChattingPageDisplayLogic: class
{
    func displaySomething(viewModel: ChattingPage.ViewModel)
}

class ChattingPageViewController: UIViewController, ChattingPageDisplayLogic
{
    var interactor: ChattingPageBusinessLogic?
    var router: (NSObjectProtocol & ChattingPageRoutingLogic & ChattingPageDataPassing)?
    
    var displayName: String?
    var email: String?
    var userID: String?
    private let messages = [ChattingPage.Response.init(message: "My first message", sender: "User 1", isIncoming: true), ChattingPage.Response.init(message: "Somewhat maybe a long message about how my day was", sender: "User 1", isIncoming: true), ChattingPage.Response.init(message: "Very lengthy message on what exactly happened to me the whole day and how I have spent my weekend off just doing some coding and writing tutorials", sender: nil, isIncoming: false)]
    
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ChattingPageInteractor()
        let presenter = ChattingPagePresenter()
        let router = ChattingPageRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
        tableView.register(MessagesTableViewCell.self, forCellReuseIdentifier: "MessagesTableViewCell")
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.navigationItem.setHidesBackButton(true, animated: true);
    }
    
    // MARK: Do something
    
    @IBOutlet weak var tableView: UITableView!
    
    
    @IBAction func signOutButtonTapped(_ sender: Any) {
        let request = ChattingPage.Request()
        interactor?.messageInfo(request: request)
    }
    
    
    func displaySomething(viewModel: ChattingPage.ViewModel)
    {
        router?.routeToSomewhere(segue: nil)
    }
}
extension ChattingPageViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return messages.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "MessagesTableViewCell", for: indexPath) as! MessagesTableViewCell
        cell.configure(with: messages[indexPath.row])
        return cell
    }
}

