//
//  ChattingPageWorker.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

class ChattingPageWorker
{
    func signOut()
    {
        do {
            try Auth.auth().signOut()
        } catch (let error) {
            print(error.localizedDescription)
        }
    }
    
    func getMessages() {
        
        let messageDB = Database.database().reference().child("Messages")
        messageDB.observe(.childAdded) { (snapshot) in
            let snapshotValue = snapshot.value as! Dictionary<String, String>
            guard let message = snapshotValue["message"], let sender = snapshotValue["sender"] else {return}
            let isIncoming = (sender == Auth.auth().currentUser?.email ? false : true)
            let chatMessage = ChattingPage.Response.init(message: message, sender: sender, isIncoming: isIncoming)
        }
    }
}
