//
//  ChattingPageInteractor.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChattingPageBusinessLogic
{
  func doSomething(request: ChattingPage.Something.Request)
}

protocol ChattingPageDataStore
{
  //var name: String { get set }
}

class ChattingPageInteractor: ChattingPageBusinessLogic, ChattingPageDataStore
{
  var presenter: ChattingPagePresentationLogic?
  var worker: ChattingPageWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ChattingPage.Something.Request)
  {
    worker = ChattingPageWorker()
    worker?.doSomeWork()
    
    let response = ChattingPage.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
