//
//  ChattingPageInteractor.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChattingPageBusinessLogic
{
    func messageInfo(request: ChattingPage.Request)
}

protocol ChattingPageDataStore
{
    var displayName: String? { get set }
    var email: String? { get set }
    var userID: String? { get set }
}

class ChattingPageInteractor: ChattingPageBusinessLogic, ChattingPageDataStore
{
    var userID: String?
    var displayName: String?
    var email: String?
    
    var presenter: ChattingPagePresentationLogic?
    var worker: ChattingPageWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func messageInfo(request: ChattingPage.Request)
    {
        worker = ChattingPageWorker()
        worker?.signOut()
        
//        let response = ChattingPage.Response(message: String?, sender: String?, isIncoming: Bool?)
//        presenter?.presentSomething(response: response)
    }
}
