//
//  ChattingPagePresenter.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChattingPagePresentationLogic
{
  func presentSomething(response: ChattingPage.Response)
}

class ChattingPagePresenter: ChattingPagePresentationLogic
{
  weak var viewController: ChattingPageDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ChattingPage.Response)
  {
    let viewModel = ChattingPage.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
