//
//  LoginPageWorker.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase
import FirebaseAuth

class LoginPageWorker
{
    var email: String?
    var password: String?
    
    func fetchLoginInfo(requestModel: LoginPage.Request,completion: @escaping (AuthDataResult?) -> Void) {
        Auth.auth().signIn(withEmail: requestModel.email ?? "", password: requestModel.password ?? "") { (data, error) in
            if let _error = error {
                //something bad happening
                print(_error.localizedDescription )
            } else {
                completion(data)
            }
        }
    }
}

