//
//  LoginPageModels.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LoginPage
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        var email: String?
        var password: String?
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
