//
//  LoginPageViewController.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPageDisplayLogic: class
{
    func displaySomething(viewModel: LoginPage.ViewModel)
}

class LoginPageViewController: UIViewController, LoginPageDisplayLogic
{
    var interactor: LoginPageBusinessLogic?
    var router: (NSObjectProtocol & LoginPageRoutingLogic & LoginPageDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = LoginPageInteractor()
        let presenter = LoginPagePresenter()
        let router = LoginPageRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
    }
    
    // MARK: Do something
    
    @IBOutlet weak var emailTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!

    @IBAction func forgotPasswordButtonTapped(_ sender: Any) {
    }
    @IBAction func loginButtonTapped(_ sender: Any) {
        let email = emailTextField.text!
        let password = passwordTextField.text!
        // MARK: Misc
        if(Validation.isValidEmail(email: email) && Validation.isValidPassword(password: password)) {
            let request = LoginPage.Request(email: email, password: password)
            interactor?.loginInfo(request: request)
        } else {
            AlertManager.showConfirmAlert(title: "Warning!", message: "Please enter a valid credentials.", buttonTitle: "OK", controller: self)
        }
    }
    
    
    func displaySomething(viewModel: LoginPage.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
