//
//  LoginPagePresenter.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPagePresentationLogic
{
  func presentSomething(response: LoginPage.Something.Response)
}

class LoginPagePresenter: LoginPagePresentationLogic
{
  weak var viewController: LoginPageDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: LoginPage.Something.Response)
  {
    let viewModel = LoginPage.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
