//
//  LoginPageInteractor.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPageBusinessLogic
{
  func doSomething(request: LoginPage.Something.Request)
}

protocol LoginPageDataStore
{
  //var name: String { get set }
}

class LoginPageInteractor: LoginPageBusinessLogic, LoginPageDataStore
{
  var presenter: LoginPagePresentationLogic?
  var worker: LoginPageWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: LoginPage.Something.Request)
  {
    worker = LoginPageWorker()
    worker?.fetchLoginInfo()
    
    let response = LoginPage.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
