//
//  LoginPageRouter.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginPageRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LoginPageDataPassing
{
  var dataStore: LoginPageDataStore? { get }
}

class LoginPageRouter: NSObject, LoginPageRoutingLogic, LoginPageDataPassing
{
  weak var viewController: LoginPageViewController?
  var dataStore: LoginPageDataStore?
  
  // MARK: Routing
  
  func routeToSomewhere(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! ChattingPageViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "LoginPageViewController") as! ChattingPageViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: LoginPageViewController, destination: ChattingPageViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: LoginPageDataStore, destination: inout ChattingPageDataStore)
  {
    destination.displayName = source.displayName
    destination.email = source.email
    destination.userID = source.uid
  }
}
