//
//  LoginPageInteractor.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPageBusinessLogic
{
    func loginInfo(request: LoginPage.Request)
}

protocol LoginPageDataStore
{
    //var name: String { get set }
    var displayName: String? { get set }
    var email: String? { get set }
    var uid: String? { get set }
}

class LoginPageInteractor: LoginPageBusinessLogic, LoginPageDataStore
{
    var displayName: String?
    var email: String?
    var uid: String?
    
    var presenter: LoginPagePresentationLogic?
    var worker: LoginPageWorker?
    
    // MARK: Do something
    
    func loginInfo(request: LoginPage.Request)
    {
        var response = LoginPage.Response()
        worker = LoginPageWorker()
        worker?.fetchLoginInfo(requestModel: request, completion: { (authResponse) in
            response.displayName = authResponse?.user.displayName
            response.email = authResponse?.user.email
            response.userID = authResponse?.user.uid
            
            // Filling data store
            self.displayName = response.displayName
            self.email = response.email
            self.uid = response.userID
        })
        presenter?.presentSomething(response: response)
    }
}
