//
//  ForgotPasswordPageInteractor.swift
//  Chatty
//
//  Created by Oguz Tandogan on 14.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPasswordPageBusinessLogic
{
  func userInfo(request: ForgotPasswordPage.Request)
}

protocol ForgotPasswordPageDataStore
{
  //var name: String { get set }
}

class ForgotPasswordPageInteractor: ForgotPasswordPageBusinessLogic, ForgotPasswordPageDataStore
{
  var presenter: ForgotPasswordPagePresentationLogic?
  var worker: ForgotPasswordPageWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func userInfo(request: ForgotPasswordPage.Request)
  {
    worker = ForgotPasswordPageWorker()
    worker?.resetPassword(resetPasswordRequestModel: request)
    
    let response = ForgotPasswordPage.Response()
    presenter?.presentSomething(response: response)
  }
}
