//
//  ForgotPasswordPageViewController.swift
//  Chatty
//
//  Created by Oguz Tandogan on 14.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPasswordPageDisplayLogic: class
{
    func displaySomething(viewModel: ForgotPasswordPage.ViewModel)
}

class ForgotPasswordPageViewController: UIViewController, ForgotPasswordPageDisplayLogic
{
    var interactor: ForgotPasswordPageBusinessLogic?
    var router: (NSObjectProtocol & ForgotPasswordPageRoutingLogic & ForgotPasswordPageDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ForgotPasswordPageInteractor()
        let presenter = ForgotPasswordPagePresenter()
        let router = ForgotPasswordPageRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
    }
    
    // MARK: Do something
    
    @IBOutlet weak var emailTextField: UITextField!
    
    @IBAction func resetPasswordButtonTapped(_ sender: Any) {
        // MARK: User info
        let email = emailTextField.text!
        
        // MARK: Misc
        if(Validation.isValidEmail(email: email)) {
            let request = ForgotPasswordPage.Request(email: email)
            interactor?.userInfo(request: request)
        } else {
            print("Please enter a valid email address")
        }
        
    }
    
    func displaySomething(viewModel: ForgotPasswordPage.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
