//
//  ForgotPasswordPageWorker.swift
//  Chatty
//
//  Created by Oguz Tandogan on 14.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Firebase

class ForgotPasswordPageWorker
{
    typealias ErrorHandler = (Result<Any, Error>) -> Void
    
//    func resetPassword(resetPasswordRequestModel: ForgotPasswordPage.Request, completion: @escaping ErrorHandler) {
//        Auth.auth().sendPasswordReset(withEmail: resetPasswordRequestModel.email ?? "") { data, error in
//            guard let data = data, error == nil else { return }
//            do {
//                try completion(.success(data))
//            } catch let error as! Error {
//                completion(.failure(error))
//            }
//        }
//    }
//
    func resetPassword(resetPasswordRequestModel: ForgotPasswordPage.Request) {
        Auth.auth().sendPasswordReset(withEmail: resetPasswordRequestModel.email ?? "") { error in
            if let _error = error {
                //something bad happning
                print(_error.localizedDescription )
            }else{
                //user registered successfully
                print("success")
            }
        }
    }
}
