//
//  ForgotPasswordPageModels.swift
//  Chatty
//
//  Created by Oguz Tandogan on 14.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ForgotPasswordPage
{
    // MARK: Use cases
    
    struct Request
    {
        var email: String?
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
}
