//
//  RegisterPageRouter.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegisterPageRoutingLogic
{
  func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol RegisterPageDataPassing
{
  var dataStore: RegisterPageDataStore? { get }
}

class RegisterPageRouter: NSObject, RegisterPageRoutingLogic, RegisterPageDataPassing
{
  weak var viewController: RegisterPageViewController?
  var dataStore: RegisterPageDataStore?
  
  // MARK: Routing
  
  func routeToSomewhere(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! LoginPageViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "LoginPageViewController") as! LoginPageViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  }

   // MARK: Navigation
  
  func navigateToSomewhere(source: RegisterPageViewController, destination: LoginPageViewController)
  {
    source.navigationController?.popViewController(animated: true)
  }
  
   // MARK: Passing data
  
  func passDataToSomewhere(source: RegisterPageDataStore, destination: inout LoginPageDataStore )
  {
//    destination.name = source.name
  }
}
