//
//  RegisterPageInteractor.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPageBusinessLogic
{
  func userInfo(request: RegisterPage.Request)
}

protocol RegisterPageDataStore
{
  //var name: String { get set }
}

class RegisterPageInteractor: RegisterPageBusinessLogic, RegisterPageDataStore
{
  var presenter: RegisterPagePresentationLogic?
  var worker: RegisterPageWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func userInfo(request: RegisterPage.Request)
  {
    worker = RegisterPageWorker()
    worker?.fetchRegisterInfo()
    
    let response = RegisterPage.Response()
    presenter?.presentSomething(response: response)
  }
}
