//
//  RegisterPageViewController.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPageDisplayLogic: class
{
    func displaySomething(viewModel: RegisterPage.ViewModel)
}

class RegisterPageViewController: UIViewController, RegisterPageDisplayLogic
{
    var interactor: RegisterPageBusinessLogic?
    var router: (NSObjectProtocol & RegisterPageRoutingLogic & RegisterPageDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = RegisterPageInteractor()
        let presenter = RegisterPagePresenter()
        let router = RegisterPageRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        //        doSomething()
    }
    
    // MARK: Do something
    
    @IBOutlet weak var emailTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    @IBOutlet weak var rePasswordTextField: UITextField!
    
    @IBAction func registerButtonTapped(_ sender: Any) {
        // MARK: User info
        let email = emailTextField.text!
        let password = passwordTextField.text!
        
        // MARK: Misc
        if (passwordTextField.text == rePasswordTextField.text) {
            let request = RegisterPage.Request(email: email, password: password)
            interactor?.userInfo(request: request)
        } else {
            print("passwords are not matching!")
        }
    }
    
    func displaySomething(viewModel: RegisterPage.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
