//
//  RegisterPageWorker.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

class RegisterPageWorker
{
    var registerRequestModel = RegisterPage.Request()
    
    func fetchRegisterInfo() {
        
        Auth.auth().createUser(withEmail: registerRequestModel.email ?? "", password: registerRequestModel.password ?? "") { (user, error) in
            if(error != nil){
                print(error)
                return
            }
        }
    }
}
