//
//  RegisterPagePresenter.swift
//  Chatty
//
//  Created by Oguz Tandogan on 11.04.2020.
//  Copyright (c) 2020 Oguz Tandogan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPagePresentationLogic
{
    func presentSomething(response: RegisterPage.Response)
}

class RegisterPagePresenter: RegisterPagePresentationLogic
{
    weak var viewController: RegisterPageDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: RegisterPage.Response)
    {
        let viewModel = RegisterPage.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)

//        if(!response.isEmailVerified!) {
//            let title = "Activation"
//            let message = "The activation email was send to your email. Please activate your account."
//            let buttonTitle = "OK"
//            AlertManager.showConfirmAlert(title: title, message: message, buttonTitle: buttonTitle, controller: viewController as! UIViewController)
//        }
    }
}
